Skip test-sysroot.js on s390x
Mitigates: #1025532

diff --git a/debian/tests/gnome-desktop-testing b/debian/tests/gnome-desktop-testing
--- a/debian/tests/gnome-desktop-testing
+++ b/debian/tests/gnome-desktop-testing
@@ -11,7 +11,9 @@ unset http_proxy
 unset https_proxy
 unset no_proxy
 
-tests="$(gnome-desktop-testing-runner -l libostree | while read -r t; do
+namespace=libostree/
+
+tests="$(gnome-desktop-testing-runner -l "$namespace" | while read -r t; do
 	t="${t%% *}"
 
 	case "$t" in
@@ -20,10 +22,23 @@ tests="$(gnome-desktop-testing-runner -l libostree | while read -r t; do
 			# https://github.com/ostreedev/ostree/issues/1620
 			continue
 			;;
+
+		(libostree/test-sysroot.js.test)
+			# https://bugs.debian.org/1025532
+			# https://github.com/ostreedev/ostree/issues/2527
+			if [ "${DEB_HOST_ARCH-}" = s390x ] || [ "$(uname -m)" = s390x ]; then
+				continue
+			fi
+			;;
 	esac
 
 	echo "$t"
 done)"
+
+if [ -z "$tests" ]; then
+	echo "Error: no installed-tests found matching $namespace" >&2
+	exit 1
+fi
 
 # Deliberately word-splitting
 # shellcheck disable=SC2046
